-- Drop the tables if they exist
USE project;
DROP TABLE IF EXISTS `spring_session_attributes`;
DROP TABLE IF EXISTS `userlist`;
DROP TABLE IF EXISTS `spring_session`;

CREATE TABLE IF NOT EXISTS `SPRING_SESSION` (
  `PRIMARY_ID` VARCHAR(255) NOT NULL,
  `SESSION_ID` VARCHAR(255) NOT NULL UNIQUE,
  `CREATION_TIME` BIGINT NOT NULL,
  `LAST_ACCESS_TIME` BIGINT NOT NULL,
  `MAX_INACTIVE_INTERVAL` INT NOT NULL,
  `EXPIRY_TIME` BIGINT NOT NULL,
  `PRINCIPAL_NAME` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`PRIMARY_ID`),
  INDEX `SPRING_SESSION_IX1` (`EXPIRY_TIME`),
  INDEX `SPRING_SESSION_IX2` (`SESSION_ID`),
  INDEX `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
);

CREATE TABLE IF NOT EXISTS `SPRING_SESSION_ATTRIBUTES` (
  `SESSION_PRIMARY_ID` VARCHAR(255) NOT NULL,
  `ATTRIBUTE_NAME` VARCHAR(255) NOT NULL,
  `ATTRIBUTE_BYTES` BLOB,
  PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`),
  CONSTRAINT `FK_SESSION_ATTRIBUTES_SESSION`
    FOREIGN KEY (`SESSION_PRIMARY_ID`)
    REFERENCES `SPRING_SESSION` (`PRIMARY_ID`)
    ON DELETE CASCADE
);

-- Create the `userlist` table
CREATE TABLE `userlist` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `mobilenumber` VARCHAR(20) COLLATE utf8mb4_0900_as_cs NOT NULL,
  `password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `gender` INT NOT NULL,
  `role` INT NOT NULL,
  `creation_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `validtill` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `mobile_number` (`mobilenumber`),
  CONSTRAINT `userlist_chk_1` CHECK ((`gender` IN (1,2,3))),
  CONSTRAINT `userlist_chk_2` CHECK ((`role` IN (1,2,4)))
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;
